name: TheRun
version: 1.0a
description: この電車は、山手線内回り、東京行きです。
author: mk499490

main: com.horizonbagel.therun.Main #com.tosogame.third.tosogame3.Main

commands:
  hey:
    description: test
    usage: /hey
  tr create:
    description: Shows a hello message to the player
    usage:
      /<command> shows a hello message to the player